---
title: "Broadband access in lower education and the achievement gap"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r libraries, include = FALSE}
library(tidyverse)
library(here)
```

```{r data}
# percent students with Internet access at home, at school level (2015-2019)
# via https://docs.google.com/spreadsheets/d/1OUny4n_4ssCkCJDtFuHFWJ7jJkO1DfhbERl5_O1oDs0/edit#gid=1261416180
dlmi <- read.csv(here("data", "NC_Students_with_Internet_Access_at_Home.csv"))
dlmi <- dlmi %>% 
  mutate(Fiscal.Year = as.numeric(substring(Fiscal.Year, 1, 4))) %>% 
  rename(year = Fiscal.Year, number = School.Code, name = School.Name, level = SchoolLevel,
         access = X223.....of.Students.with.Home.Internet.Access) %>% 
  select(-Average.DailyMembershipRange, -EconomicallyDisadvantagedRange)
dlmi$access[dlmi$access == "-"] <- NA
dlmi$level[dlmi$level == "-"] <- NA
dlmi <- dlmi %>% 
  arrange(name, year)

# percent students with Internet access at home, at school level, by percentages (2019)
dlmi_2019 <- dlmi %>% 
  filter(year == 2019)

# percent students with Internet access at home, at school level, by percentage ranges (2015-2019)
# for multi year comparison
dlmi_range_2015 <- dlmi %>% 
  filter(year != 2019)
dlmi_range_2019 <- dlmi %>% 
  filter(year == 2019) %>% 
  mutate(access = as.numeric(access)) %>% 
  mutate(access = case_when(access >= 0 & access <= 25 ~ "0-25", access > 25 & access <= 50 ~ "26-50",
                            access > 50 & access <= 75 ~ "51-75", access > 75 & access <= 100 ~ "76-100"))
dlmi <- rbind(dlmi_range_2015, dlmi_range_2019) %>% 
  arrange(name, year)

# number of students by race and sex, at school level (2019)
ncdpi_race <- read.csv(here("data", "NCDPI_Race.csv"))
ncdpi_race <- ncdpi_race %>% 
  mutate(LEA = as.character(LEA), School = as.character(School))
ncdpi_race$LEA[as.numeric(ncdpi_race$LEA) < 100] <- paste0("0", ncdpi_race$LEA)
ncdpi_race <- ncdpi_race %>% 
  mutate(number = paste0(LEA, School)) %>%
  rename(year = Year, district = X____LEA.Name____, name = X___School.Name___,
         indigenous_m = Indian.Male, indigenous_f = Indian.Female, 
         asian_m = Asian.Male, asian_f = Asian.Female,
         hispanic_m = Hispanic.Male, hispanic_f = Hispanic.Female,
         black_m = Black.Male, black_f = Black.Female,
         white_m = White.Male, white_f = White.Female,
         pi_m = Pacific.Island.Male, pi_f = Pacific.Island.Female,
         bi_m = Two.or..More.Male, bi_f = Two.or..More.Female, total = Total) %>% 
  select(-LEA, -School)

# percent economically disadvantaged students, at school level (2017-2019)
ncdpi_eds <- read.csv(here("data", "NCDPI_EDS.csv"))
ncdpi_eds <- ncdpi_eds %>% 
  filter(!is.na(as.numeric(agency_code))) %>% 
  rename(number = agency_code) %>% 
  select(-pct_eds_masking)

# (recurring) low performance designations, at school level (2018-2019)
ncdpi_low_perf <- read.csv(here("data", "NCDPI_Low_Performance.csv"))
ncdpi_low_perf <- ncdpi_low_perf %>% 
  filter(!is.na(as.numeric(agency_code))) %>% 
  rename(number = agency_code, lp = lp_school, rlp = rlp_school) %>% 
  select(year, number, lp, rlp)

# joining access and demographic datasets, losing 404 schools
dlmi_2019 <- inner_join(dlmi_2019, ncdpi_race) %>% 
  mutate(access = as.numeric(access), total = as.numeric(gsub(",", "", total)))
dlmi_2019 <- inner_join(dlmi_2019, ncdpi_eds)
```

```{r summary_statistics}
# 91 schools missing access data
dlmi %>% 
  count(year, is.na(access))

# 116 schools not included in DLMI
anti_join(ncdpi_race, dlmi_2019, by = "number")

# identify schools without observations for all five years
dlmi %>% 
  count(name) %>% 
  filter(n != 5)

# number of schools reporting DLMI inconsistent across five years
dlmi %>% 
  count(year)

# some districts do not report DLMI data at all
dlmi_2019 %>% 
  count(district)
ncdpi_race %>% 
  count(district)
```

```{r analysis}
# count access by year
dlmi %>% 
  count(year, access) %>% 
  group_by(year) %>% 
  mutate(prop = n / sum(n))

# calculate proportion of low performing schools for each range
filter(inner_join(dlmi, ncdpi_low_perf), year == 2019) %>% 
  count(access, lp) %>% 
  group_by(access) %>% 
  mutate(prop = n / sum(n))

# identify schools that experienced decrease in access from 2015 to 2019
# 176 schools experienced such decrease
dlmi_decrease <- dlmi %>% 
  filter(year == 2015 | year == 2019) %>% 
  group_by(number) %>% 
  pivot_wider(names_from = year, values_from = access) %>% 
  filter(!is.na(`2015`) & !is.na(`2019`) & `2015` != `2019`) %>% 
  filter(as.numeric(substring(`2015`, 1, 2)) > as.numeric(substring(`2019`, 1, 2)) | 
           as.numeric(substring(`2019`, 1, 1)) == 0) %>% 
  ungroup() %>% 
  inner_join(., ncdpi_race) %>% 
  inner_join(., ncdpi_eds) %>% 
  select(-year) %>% 
  mutate(total = as.numeric(gsub(",", "", total)))
dlmi_decrease$`2019_actual` <- filter(dlmi_2019, number %in% dlmi_decrease$number)$access
dlmi_decrease <- dlmi_decrease %>% 
  mutate(`2019_low` = as.numeric(substring(`2015`, 1, 2)) - `2019_actual`,
         `2019_high` = as.numeric(substring(`2015`, 4)) - `2019_actual`)
dlmi_decrease <- dlmi_decrease[, c(1:5, 23:25, 6:22)]

# count number of districts and school types experiencing decrease
dlmi_decrease %>% 
  count(district)
dlmi_decrease %>% 
  count(level)

# count number of schools experiencing decrease which are majority minority or eds
dlmi_decrease %>% 
  count((total - white_m - white_f) / total >= 0.5)
dlmi_decrease %>% 
  count(pct_eds >= 50)

# count number of schools experiencing at least 10% decrease
dlmi_decrease %>% 
  filter(`2019_low` >= 10)

# calculate access means & medians for state & each district (2019)
# 83% mean, 89% median
dlmi_2019 %>% 
  summarize(mean = mean(access, na.rm = TRUE), median = median(access, na.rm = TRUE))

dlmi_2019 %>% 
  group_by(district) %>% 
  summarize(mean = mean(access, na.rm = TRUE), median = median(access, na.rm = TRUE)) %>% 
  arrange(mean)

# identify schools with below average access for state & that district (2019)
# 824 schools were below state average 
dlmi_2019 %>% 
  filter(!is.na(access)) %>% 
  filter(access < mean(access))
# 851 schools were below district average
dlmi_2019 %>%
  filter(!is.na(access)) %>% 
  group_by(district) %>% 
  filter(access < mean(access))
# 155 schools had below half with access
dlmi_2019 %>%
  filter(!is.na(access)) %>% 
  group_by(district) %>% 
  filter(access <= 50) %>% 
  ungroup() %>% 
  count((total - white_m - white_f) / total >= 0.5, pct_eds >= 50)

# calculate proportion of schools with below half access for each district
dlmi_2019_prop <- dlmi_2019 %>% 
  filter(!is.na(access)) %>% 
  group_by(district) %>% 
  count(access <= 50) %>% 
  filter(`access <= 50`)
dlmi_2019_prop$sum <- filter(count(ncdpi_race, vars = district), vars %in% dlmi_2019_prop$district)$n
dlmi_2019_prop <- dlmi_2019_prop %>% 
  mutate(prop = n / sum) %>% 
  select(district, n, sum, prop) %>% 
  arrange(desc(prop))

# count number of schools with majority minority (1156/2236)
# count number of majority minority schools with below average access (502/1156)
# count number of majority white schools with below average access (322/1080)
dlmi_2019 %>%
  filter(!is.na(access)) %>% 
  count((total - white_m - white_f) / total >= 0.5, access < mean(access))

# count number of majority minority schools with less than half access (111/1156)
# count number of majority white schools with less than half access (44/1080)
dlmi_2019 %>%
  filter(!is.na(access)) %>% 
  count((total - white_m - white_f) / total >= 0.5, access <= 50)

# count number of schools with majority economically disadvantaged "eds" (1250/2236)
# count number of majority eds schools with below average access (587/1250)
# count number of majority not eds with below average access (236/984)
dlmi_2019 %>% 
  filter(!is.na(access)) %>% 
  count(pct_eds >= 50, access < mean(access))

# count number of majority eds schools with less than half access (116/1250)
# count number of majority not eds schools with less than half access (38/984)
dlmi_2019 %>% 
  filter(!is.na(access)) %>% 
  count(pct_eds >= 50, access <= 50)

# count number of majority minority and eds schools with below average access (416)
dlmi_2019 %>% 
  filter(!is.na(access)) %>% 
  count((total - white_m - white_f) / total >= 0.5, pct_eds >= 50, access < mean(access))
```

```{r viz}
# number of schools in each bucket from 2015 to 2019
dlmi %>% 
  group_by(name) %>% 
  filter(n() == 5) %>% 
  ungroup() %>% 
  count(year, access) %>% 
  filter(!is.na(access)) %>% 
  ggplot(data = ., mapping = aes(x = year, y = n, fill = access)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_viridis_d() +
  labs(x = "Year", y = "Number", fill = "Percent with\nHome Internet\nAccess") +
  theme_classic()

# race & access
dlmi_2019 %>% 
  mutate(pct_min = (total - white_m - white_f) / total * 100) %>% 
  ggplot(data = ., mapping = aes(x = pct_min, y = access)) +
  geom_point(alpha = 0.25) +
  labs(x = "Percent Minority", y = "Percent with Home Internet Access") +
  theme_classic()

# economic disadvantage & access
ggplot(data = dlmi_2019, mapping = aes(x = pct_eds, y = access)) +
  geom_point(alpha = 0.25) +
  labs(x = "Percent Economically Disadvantaged", y = "Percent with Home Internet Access") +
  scale_x_continuous(limits = c(0, 100)) +
  theme_classic()
```

```{r peer_analysis}
below_half <- dlmi_2019 %>%
  group_by(district) %>%  
  arrange(access, .by_group = T) %>% 
  filter(access <= 50) %>% 
  ungroup() %>% 
  mutate(access = access / 100, 
         pct_eds = pct_eds / 100, 
         pct_min = (total - white_m - white_f) / total) %>% 
  filter(!is.na(access) & !is.na(pct_eds) & !is.na(pct_min)) %>% 
  mutate(group = row_number(), diff = 0)

dlmi_peers <- below_half[1,] 

for (i in 2:nrow(below_half)) {
  school <- below_half[i,]
  peers <- dlmi_2019 %>% 
    mutate(access = access / 100, 
           pct_eds = pct_eds / 100,
           pct_min = (total - white_m - white_f) / total) %>% 
    filter(!is.na(access) & !is.na(pct_eds) & !is.na(pct_min)) %>% 
    filter(district == school$district & level == school$level, 
           total > school$total - 50, total < school$total + 50,
           pct_eds > school$pct_eds - 0.05, pct_eds < school$pct_eds + 0.05,
           pct_min > school$pct_min - 0.05, pct_min < school$pct_min + 0.05) %>% 
    arrange(access) %>% 
    filter(name != school$name, !name %in% dlmi_peers$name) %>%
    mutate(group = school$group, diff = access - school$access)
  dlmi_peers <- bind_rows(dlmi_peers, school, peers)
}

dlmi_peers <- dlmi_peers %>% 
  group_by(name) %>% 
  slice(1) %>% 
  ungroup() %>% 
  group_by(group) %>% 
  arrange(group, access) %>% 
  inner_join(., ncdpi_low_perf)
```